name: centos-dist
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/centos.yml'
      - '!centos/**'
  workflow_dispatch:
  repository_dispatch:
    types: centos-build

jobs:
  build:
    name: Building centos docker images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dist:
          - {
              name: centos-6,
              os: centos,
              symbol: 6,
              platforms: "linux/amd64"
            }
          - {
              name: centos-7,
              os: centos,
              symbol: 7,
              platforms: "linux/amd64"
            }
          - {
              name: centos-8,
              os: centos,
              symbol: 8,
              platforms: "linux/amd64,linux/arm64/v8"
            }
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Prepare
        id: prepare
        run: |
          DIST_NAME=${{ matrix.dist.name }}
          USER_NAME=flameshotorg
          REPO_NAME=ci-building-images
          IMAGE_NAME=${{ matrix.dist.os }}/${{ matrix.dist.symbol }}
          TAGS="${USER_NAME}/${REPO_NAME}:${DIST_NAME}"
          echo "build_args=VERSION=${DIST_NAME}" >> $GITHUB_OUTPUT
          echo "image-name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./${{ steps.prepare.outputs.image-name }}
          file: ./${{ steps.prepare.outputs.image-name }}/Dockerfile
          platforms: ${{ matrix.dist.platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          tags: ${{ steps.prepare.outputs.tags }}
      - name: Clear
        if: always()
        run: |
          rm -rf ${HOME}/.docker/config.json